### ISSUE TITLE
Getting `warning: Cannot find the PR id` when attempting to use reporting action

### ISSUE THREAD

**Issue by csaunders-humi** [aki77/simplecov-report-action#20]
When attempting to integrate this into a github action that takes in aggregated coverage reports I am getting the warning message mentioned in the title. I've looked around to see if anyone else has had a similar issue and I am thinking that [actions/toolkit #289](https://github.com/actions/toolkit/issues/289) might have exhibited similar behaviour.

It appears that the fix on that project was to check several [different potential sources](https://github.com/actions/toolkit/pull/311/files#diff-63637ee936ae11c19c1f85ad2393274ff10a234beb21e8848b147ea2f992a443R47) for the issue number.

It's also entirely possible that I'm not using this action as it was originally intended.

----------------------

Here is the portion of my github action that is supposed to be generating the report:

```yml
      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          path: coverage/ # contains several directories (i.e. coverage/{group_one,group_two,...}/.resultset.json)

      - name: Collate reports
        run: ./github_scripts/coverage_report # generates a collated report which includes coverage/.resultset.json and coverage/.last_run.json

      - name: Create tarball of reports
        run: tar -czvf rspec-coverage-report.tar.gz coverage/

      - name: Upload collated coverage report
        uses: actions/upload-artifact@v2
        with:
          path: rspec-coverage-report.tar.gz

      - name: Generate Github coverage comment
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

Output from github actions page

![image](https://user-images.githubusercontent.com/90268659/141484811-e4b34cd7-fee3-4c2b-b86a-5e5f0f61c735.png)
